# Generated by Django 4.1.7 on 2023-03-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Rut de la empresa"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=30, verbose_name="Nombre de la empresa"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        max_length=50, verbose_name="Dirección de la empresa"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=15, verbose_name="Télefono de la empresa"
                    ),
                ),
            ],
        ),
    ]
